query PermissionList(
  $cursor: PermissionWhereUniqueInput
  $distinct: [PermissionScalarFieldEnum!]
  $orderBy: [PermissionOrderByWithRelationInput!]
  $skip: Int
  $take: Int
  $where: PermissionWhereInput
) {
  findManyPermissions(
    cursor: $cursor
    distinct: $distinct
    orderBy: $orderBy
    skip: $skip
    take: $take
    where: $where
  ) {
    id
    operation
    tableName
  }
}
