query UserDetail($where: UserWhereUniqueInput!) {
  findUniqueUser(where: $where) {
    confirmationCode
    createdAt
    email
    emailConfirmedAt
    id
    name
    permissions {
      id
      tableName
      operation
    }
    role {
      id
      name
    }
    roleId
    updatedAt
  }
}
